export const FAILURE_CLASSES = [
  "GROUND_TRUTH_FAILURE",
  "AGENT_OUTPUT_FAILURE",
  "UI_CONTRACT_FAILURE",
  "UI_RENDERING_FAILURE",
  "DATA_TRANSFORMATION_FAILURE",
  "GROUNDEDNESS_FAILURE",
  "TEST_EXECUTION_FAILURE",
  "VALIDATION_UNCERTAIN",
] as const;

export type FailureClass = (typeof FAILURE_CLASSES)[number];

export type CheckStatus = "PASS" | "FAIL" | "SKIPPED" | "UNCERTAIN";
